// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5cLr25mBDQMfP4n7R98Mkx4b5UnnW0-Y',
    appId: '1:677849282006:web:3343008d9e08dbe23ca077',
    messagingSenderId: '677849282006',
    projectId: 'firstproject-d4180',
    authDomain: 'firstproject-d4180.firebaseapp.com',
    storageBucket: 'firstproject-d4180.appspot.com',
    measurementId: 'G-B7G68YPWVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLQkz5T0DL0SzFCDczL1nrC79X0mgXbvA',
    appId: '1:677849282006:android:16966cb847a544df3ca077',
    messagingSenderId: '677849282006',
    projectId: 'firstproject-d4180',
    storageBucket: 'firstproject-d4180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJyk4pfld3hiQdcVs7lurzyFuivoO0jRE',
    appId: '1:677849282006:ios:1ea853f8b2c34b3f3ca077',
    messagingSenderId: '677849282006',
    projectId: 'firstproject-d4180',
    storageBucket: 'firstproject-d4180.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJyk4pfld3hiQdcVs7lurzyFuivoO0jRE',
    appId: '1:677849282006:ios:1ea853f8b2c34b3f3ca077',
    messagingSenderId: '677849282006',
    projectId: 'firstproject-d4180',
    storageBucket: 'firstproject-d4180.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5cLr25mBDQMfP4n7R98Mkx4b5UnnW0-Y',
    appId: '1:677849282006:web:b0cd19315bbd22943ca077',
    messagingSenderId: '677849282006',
    projectId: 'firstproject-d4180',
    authDomain: 'firstproject-d4180.firebaseapp.com',
    storageBucket: 'firstproject-d4180.appspot.com',
    measurementId: 'G-L1FK6F4ZB1',
  );
}
